### ISSUE TITLE
Error while calculating loss

### ISSUE THREAD

**Issue by Suvi-dha** [sacmehta/YNet#2]
I have 3 classes to classify. and my input image is 512 x 512 x 3.

```
Traceback (most recent call last):
  File "main.py", line 317, in <module>
    trainValidateSegmentation(args)
  File "main.py", line 246, in trainValidateSegmentation
    train(args, trainLoaderWithZoom, model, criteria, optimizer, epoch)
  File "main.py", line 90, in train
    loss = criterion(output, target_var)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\IIITA\Documents\PHD\ICIAR2018_BACH_Challenge\YNet-master\YNet-master\stage1\Criteria.py", line 21, in forward
    return self.loss(F.log_softmax(outputs),targets)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 193, in forward
    self.ignore_index, self.reduce)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1334, in nll_loss
    return torch._C._nn.nll_loss2d(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: weight tensor should be defined either for all or no classes at c:\programdata\miniconda3\condabld\pytorch_1524549877902\work\aten\src\thcunn\generic/SpatialClassNLLCriterion.cu:28
```

**Comment by sacmehta** [comment]
Could you please verify the size of weight tensor? It should have three elements.

Check output at line 162 of the stage1/main.py file.

Also, you can replace the CrossEntropyLoss2d at line 66 with torch.nn.CrossEntropyLoss. The current version of CrossEntropyLoss in Pytorch supports multi-dimensions.

**Comment by Suvi-dha** [comment]
I have rectified this. Thank you. However, I am now facing CUDNN INTERNAL STATUS ERROR while calculating backward loss. I have tried few workarounds given in different forums  but unable to overcome this. 

```
Traceback (most recent call last):
  File "main.py", line 318, in <module>
    trainValidateSegmentation(args)
  File "main.py", line 247, in trainValidateSegmentation
    train(args, trainLoaderWithZoom, model, criteria, optimizer, epoch)
  File "main.py", line 93, in train
    loss.backward()
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR
```
If I disable CUDNN from the code, I again counter this error 

THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\aten\src\thc\generic/THCTensorMath.cu line=15 error=77 : an illegal memory access was encountered
```
Traceback (most recent call last):
  File "main.py", line 318, in <module>
    trainValidateSegmentation(args)
  File "main.py", line 247, in trainValidateSegmentation
    train(args, trainLoaderWithZoom, model, criteria, optimizer, epoch)
  File "main.py", line 93, in train
    loss.backward()
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 83, in backward
    grad_tensors = _make_grads(tensors, grad_tensors)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 28, in _make_grads
    new_grads.append(torch.ones_like(out))
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\aten\src\thc\generic/THCTensorMath.cu:15
```
 If you know the possible reason, please let me know.

**Comment by sacmehta** [comment]
Which version of torch and cudnn are you using?

**Comment by Suvi-dha** [comment]
torch is 0.4.0 and cudnn version 7

**Comment by sacmehta** [comment]
This code supports 0.3 and 0.2

**Comment by Suvi-dha** [comment]
I changed my pytorch version from 0.4 to 0.3 but still, I am unable to work with cuda. So, i disabled it and now I am getting the following error. 

```
Network parameters: 2718283
Weights to handle class-imbalance

 4.8460
 1.5345
 7.0640
[torch.FloatTensor of size 3]

input shape=torch.Size([1, 3, 512, 512]), output shape= torch.Size([1, 512, 512])
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    trainValidateSegmentation(args)
  File "main.py", line 249, in trainValidateSegmentation
    train(args, trainLoaderWithZoom, model, criteria, optimizer, epoch)
  File "main.py", line 90, in train
    loss = criterion(output, target_var)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 679, in forward
    self.ignore_index, self.reduce)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1161, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1054, in nll_loss
    return torch._C._nn.nll_loss2d(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at **_c:\anaconda2\conda-bld\pytorch_1519501749874\work\torch\lib\thnn\generic/SpatialClassNLLCriterion.c:111_**
```

P. S. 
The file location showing during runtime error doesn't exist in my system and this same file location is thrown during cuda runtime error also.

**Comment by Suvi-dha** [comment]
finally got the code working. The problem was in annotation data. Got to understand about the root cause of the error only after disabling Cuda.  Corrected and then enabled CUda again. 
Thank you for replying back.

**Comment by AloshkaD** [comment]
@Suvi-dha I have the same problem, how did you solve it?
